//! NVENC FFI — bindings are **generated by bindgen** from the vendored
//! `nvEncodeAPI.h` (see `build.rs`), so every struct layout/size matches the SDK
//! header exactly. This module re-exports them and adds a few small helpers that
//! bindgen does not provide (version packing, status names).
//!
//! Windows-only (the crate's Windows code is `#[cfg(windows)]`).

#![allow(
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    dead_code
)]

// Pull in the generated bindings (structs, enums, GUID constants, fn-pointer table).
// They live in a sub-module so we can blanket-allow the style lints the machine-
// generated code trips (unused re-exports, and `unnecessary_transmutes` on newer
// rustc). `unknown_lints` guards against an older toolchain not knowing the latter.
#[allow(
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    dead_code,
    unused_imports,
    unknown_lints,
    unnecessary_transmutes
)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/nvenc_bindings.rs"));
}
pub use generated::*;

use std::os::raw::c_int;

pub type NVENCSTATUS_T = c_int;
pub const NV_ENC_SUCCESS_I: NVENCSTATUS_T = 0;
pub const NV_ENC_ERR_NEED_MORE_INPUT_I: NVENCSTATUS_T = 20;

/// Human-readable NVENC status name (numeric codes are easy to misread).
pub fn status_name(st: i32) -> &'static str {
    match st {
        0 => "SUCCESS",
        1 => "NO_ENCODE_DEVICE",
        2 => "UNSUPPORTED_DEVICE",
        3 => "INVALID_ENCODERDEVICE",
        4 => "INVALID_DEVICE",
        5 => "DEVICE_NOT_EXIST",
        6 => "INVALID_PTR",
        7 => "INVALID_EVENT",
        8 => "INVALID_PARAM",
        9 => "INVALID_CALL",
        10 => "OUT_OF_MEMORY",
        11 => "ENCODER_NOT_INITIALIZED",
        12 => "UNSUPPORTED_PARAM",
        13 => "LOCK_BUSY",
        14 => "NOT_ENOUGH_BUFFER",
        15 => "INVALID_VERSION",
        16 => "MAP_FAILED",
        20 => "NEED_MORE_INPUT",
        21 => "ENCODER_BUSY",
        _ => "UNKNOWN",
    }
}

/// SDK API version. The header defines NVENCAPI_MAJOR/MINOR_VERSION as macros, which
/// bindgen does NOT emit, so we provide the version packing here. Overridable at
/// runtime via env for driver-version flexibility.
pub const NVENCAPI_MAJOR_FALLBACK: u32 = 13;
pub const NVENCAPI_MINOR_FALLBACK: u32 = 0;

pub fn api_version() -> u32 {
    let major = std::env::var("G9_NVENC_MAJOR")
        .ok()
        .and_then(|s| s.parse::<u32>().ok())
        .unwrap_or(NVENCAPI_MAJOR_FALLBACK);
    let minor = std::env::var("G9_NVENC_MINOR")
        .ok()
        .and_then(|s| s.parse::<u32>().ok())
        .unwrap_or(NVENCAPI_MINOR_FALLBACK);
    major | (minor << 24)
}

/// NVENCAPI_STRUCT_VERSION(ver) = api_version | (ver<<16) | (0x7<<28)
pub fn struct_version(ver: u32) -> u32 {
    api_version() | (ver << 16) | (0x7 << 28)
}

// --- Clean, bindgen-naming-independent aliases for the enum values we use.
// --- bindgen names enum constants inconsistently (some tags carry a leading
// --- underscore, some don't), so instead of referencing the generated names we
// --- define these with the literal values straight from nvEncodeAPI.h. The enum
// --- field types are all `c_int` type-aliases, so i32 literals assign cleanly.
pub const NV_ENC_DEVICE_TYPE_DIRECTX: i32 = 0; // DIRECTX=0, CUDA=1, OPENGL=2
pub const NV_ENC_PARAMS_RC_CBR: i32 = 2;
pub const NV_ENC_PARAMS_RC_VBR: i32 = 1;
pub const NV_ENC_INPUT_RESOURCE_TYPE_DIRECTX: i32 = 0;
pub const NV_ENC_BUFFER_FORMAT_NV12: i32 = 0x00000001;
pub const NV_ENC_PIC_STRUCT_FRAME: i32 = 1;
pub const NV_ENC_PIC_FLAG_FORCEIDR: u32 = 0x2; // per header: FORCEIDR=0x2
pub const NV_ENC_PIC_FLAG_OUTPUT_SPSPPS: u32 = 0x4; // per header: OUTPUT_SPSPPS=0x4
pub const NV_ENC_TUNING_INFO_LOW_LATENCY: i32 = 2;
pub const NV_ENC_TUNING_INFO_ULTRA_LOW_LATENCY: i32 = 3;
pub const NV_ENC_TUNING_INFO_HIGH_QUALITY: i32 = 1;

// --- GUID constants, defined by VALUE from nvEncodeAPI.h.
// --- bindgen emits the header's `static const GUID` as *extern* symbols (link
// --- errors, since we load the DLL dynamically with no import lib), so we define
// --- our own consts with the exact byte values using the generated `GUID` type.
#[inline]
const fn guid(d1: u32, d2: u16, d3: u16, d4: [u8; 8]) -> GUID {
    GUID {
        Data1: d1,
        Data2: d2,
        Data3: d3,
        Data4: d4,
    }
}

pub const G9_NV_ENC_CODEC_H264_GUID: GUID = guid(
    0x6bc82762,
    0x4e63,
    0x4ca4,
    [0xaa, 0x85, 0x1e, 0x50, 0xf3, 0x21, 0xf6, 0xbf],
);
pub const G9_NV_ENC_H264_PROFILE_HIGH_GUID: GUID = guid(
    0xe7cbc309,
    0x4f7a,
    0x4b89,
    [0xaf, 0x2a, 0xd5, 0x37, 0xc9, 0x2b, 0xe3, 0x10],
);
pub const G9_NV_ENC_PRESET_P4_GUID: GUID = guid(
    0x90a7b826,
    0xdf06,
    0x4862,
    [0xb9, 0xd2, 0xcd, 0x6d, 0x73, 0xa0, 0x86, 0x81],
);
pub const G9_NV_ENC_PRESET_P5_GUID: GUID = guid(
    0x21c6e6b4,
    0x297a,
    0x4cba,
    [0x99, 0x8f, 0xb6, 0xcb, 0xde, 0x72, 0xad, 0xe3],
);
