//! NVENC FFI — bindings are **generated by bindgen** from the vendored
//! `nvEncodeAPI.h` (see `build.rs`), so every struct layout/size matches the SDK
//! header exactly. This module re-exports them and adds a few small helpers that
//! bindgen does not provide (version packing, status names).
//!
//! Windows-only (the crate's Windows code is `#[cfg(windows)]`).

#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals, dead_code)]

// Pull in the generated bindings (structs, enums, GUID constants, fn-pointer table,
// NvEncodeAPICreateInstance / NvEncodeAPIGetMaxSupportedVersion typedefs).
include!(concat!(env!("OUT_DIR"), "/nvenc_bindings.rs"));

use std::os::raw::c_int;

pub type NVENCSTATUS_T = c_int;
pub const NV_ENC_SUCCESS_I: NVENCSTATUS_T = 0;
pub const NV_ENC_ERR_NEED_MORE_INPUT_I: NVENCSTATUS_T = 20;

/// Human-readable NVENC status name (numeric codes are easy to misread).
pub fn status_name(st: i32) -> &'static str {
    match st {
        0 => "SUCCESS",
        1 => "NO_ENCODE_DEVICE",
        2 => "UNSUPPORTED_DEVICE",
        3 => "INVALID_ENCODERDEVICE",
        4 => "INVALID_DEVICE",
        5 => "DEVICE_NOT_EXIST",
        6 => "INVALID_PTR",
        7 => "INVALID_EVENT",
        8 => "INVALID_PARAM",
        9 => "INVALID_CALL",
        10 => "OUT_OF_MEMORY",
        11 => "ENCODER_NOT_INITIALIZED",
        12 => "UNSUPPORTED_PARAM",
        13 => "LOCK_BUSY",
        14 => "NOT_ENOUGH_BUFFER",
        15 => "INVALID_VERSION",
        16 => "MAP_FAILED",
        20 => "NEED_MORE_INPUT",
        21 => "ENCODER_BUSY",
        _ => "UNKNOWN",
    }
}

/// SDK API version. The header defines NVENCAPI_MAJOR/MINOR_VERSION as macros, which
/// bindgen does NOT emit, so we provide the version packing here. Overridable at
/// runtime via env for driver-version flexibility.
pub const NVENCAPI_MAJOR_FALLBACK: u32 = 13;
pub const NVENCAPI_MINOR_FALLBACK: u32 = 0;

pub fn api_version() -> u32 {
    let major = std::env::var("G9_NVENC_MAJOR")
        .ok()
        .and_then(|s| s.parse::<u32>().ok())
        .unwrap_or(NVENCAPI_MAJOR_FALLBACK);
    let minor = std::env::var("G9_NVENC_MINOR")
        .ok()
        .and_then(|s| s.parse::<u32>().ok())
        .unwrap_or(NVENCAPI_MINOR_FALLBACK);
    major | (minor << 24)
}

/// NVENCAPI_STRUCT_VERSION(ver) = api_version | (ver<<16) | (0x7<<28)
pub fn struct_version(ver: u32) -> u32 {
    api_version() | (ver << 16) | (0x7 << 28)
}
