[package]
name = "g9-webrtc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
g9-core = { path = "../g9-core" }
thiserror.workspace = true
tracing.workspace = true
bytes.workspace = true
tokio.workspace = true
async-trait.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
webrtc.workspace = true
tokio-tungstenite.workspace = true
futures.workspace = true
